// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/cluster/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterQuotaLister helps list ClusterQuotas.
// All objects returned here must be treated as read-only.
type ClusterQuotaLister interface {
	// List lists all ClusterQuotas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ClusterQuota, err error)
	// Get retrieves the ClusterQuota from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ClusterQuota, error)
	ClusterQuotaListerExpansion
}

// clusterQuotaLister implements the ClusterQuotaLister interface.
type clusterQuotaLister struct {
	indexer cache.Indexer
}

// NewClusterQuotaLister returns a new ClusterQuotaLister.
func NewClusterQuotaLister(indexer cache.Indexer) ClusterQuotaLister {
	return &clusterQuotaLister{indexer: indexer}
}

// List lists all ClusterQuotas in the indexer.
func (s *clusterQuotaLister) List(selector labels.Selector) (ret []*v1.ClusterQuota, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ClusterQuota))
	})
	return ret, err
}

// Get retrieves the ClusterQuota from the index for a given name.
func (s *clusterQuotaLister) Get(name string) (*v1.ClusterQuota, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("clusterquota"), name)
	}
	return obj.(*v1.ClusterQuota), nil
}
