// Code generated by lister-gen. DO NOT EDIT.

package v1

// ChartInfoListerExpansion allows custom methods to be added to
// ChartInfoLister.
type ChartInfoListerExpansion interface{}

// ClusterQuotaListerExpansion allows custom methods to be added to
// ClusterQuotaLister.
type ClusterQuotaListerExpansion interface{}

// FeatureListerExpansion allows custom methods to be added to
// FeatureLister.
type FeatureListerExpansion interface{}

// HelmReleaseListerExpansion allows custom methods to be added to
// HelmReleaseLister.
type HelmReleaseListerExpansion interface{}

// HelmReleaseNamespaceListerExpansion allows custom methods to be added to
// HelmReleaseNamespaceLister.
type HelmReleaseNamespaceListerExpansion interface{}

// LocalClusterAccessListerExpansion allows custom methods to be added to
// LocalClusterAccessLister.
type LocalClusterAccessListerExpansion interface{}

// SleepModeConfigListerExpansion allows custom methods to be added to
// SleepModeConfigLister.
type SleepModeConfigListerExpansion interface{}

// SleepModeConfigNamespaceListerExpansion allows custom methods to be added to
// SleepModeConfigNamespaceLister.
type SleepModeConfigNamespaceListerExpansion interface{}

// SpaceListerExpansion allows custom methods to be added to
// SpaceLister.
type SpaceListerExpansion interface{}

// VirtualClusterListerExpansion allows custom methods to be added to
// VirtualClusterLister.
type VirtualClusterListerExpansion interface{}

// VirtualClusterNamespaceListerExpansion allows custom methods to be added to
// VirtualClusterNamespaceLister.
type VirtualClusterNamespaceListerExpansion interface{}
