// Code generated by lister-gen. DO NOT EDIT.

package v1

// ChartInfoListerExpansion allows custom methods to be added to
// ChartInfoLister.
type ChartInfoListerExpansion interface{}

// FeatureListerExpansion allows custom methods to be added to
// FeatureLister.
type FeatureListerExpansion interface{}

// HelmReleaseListerExpansion allows custom methods to be added to
// HelmReleaseLister.
type HelmReleaseListerExpansion interface{}

// HelmReleaseNamespaceListerExpansion allows custom methods to be added to
// HelmReleaseNamespaceLister.
type HelmReleaseNamespaceListerExpansion interface{}
