// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	clusterv1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/cluster/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// FeatureLister helps list Features.
// All objects returned here must be treated as read-only.
type FeatureLister interface {
	// List lists all Features in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*clusterv1.Feature, err error)
	// Get retrieves the Feature from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*clusterv1.Feature, error)
	FeatureListerExpansion
}

// featureLister implements the FeatureLister interface.
type featureLister struct {
	listers.ResourceIndexer[*clusterv1.Feature]
}

// NewFeatureLister returns a new FeatureLister.
func NewFeatureLister(indexer cache.Indexer) FeatureLister {
	return &featureLister{listers.New[*clusterv1.Feature](indexer, clusterv1.Resource("feature"))}
}
