// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	clusterv1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/cluster/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalClusterAccesses implements LocalClusterAccessInterface
type FakeLocalClusterAccesses struct {
	Fake *FakeClusterV1
}

var localclusteraccessesResource = schema.GroupVersionResource{Group: "cluster.loft.sh", Version: "v1", Resource: "localclusteraccesses"}

var localclusteraccessesKind = schema.GroupVersionKind{Group: "cluster.loft.sh", Version: "v1", Kind: "LocalClusterAccess"}

// Get takes name of the localClusterAccess, and returns the corresponding localClusterAccess object, and an error if there is any.
func (c *FakeLocalClusterAccesses) Get(ctx context.Context, name string, options v1.GetOptions) (result *clusterv1.LocalClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localclusteraccessesResource, name), &clusterv1.LocalClusterAccess{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.LocalClusterAccess), err
}

// List takes label and field selectors, and returns the list of LocalClusterAccesses that match those selectors.
func (c *FakeLocalClusterAccesses) List(ctx context.Context, opts v1.ListOptions) (result *clusterv1.LocalClusterAccessList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localclusteraccessesResource, localclusteraccessesKind, opts), &clusterv1.LocalClusterAccessList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clusterv1.LocalClusterAccessList{ListMeta: obj.(*clusterv1.LocalClusterAccessList).ListMeta}
	for _, item := range obj.(*clusterv1.LocalClusterAccessList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localClusterAccesses.
func (c *FakeLocalClusterAccesses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localclusteraccessesResource, opts))
}

// Create takes the representation of a localClusterAccess and creates it.  Returns the server's representation of the localClusterAccess, and an error, if there is any.
func (c *FakeLocalClusterAccesses) Create(ctx context.Context, localClusterAccess *clusterv1.LocalClusterAccess, opts v1.CreateOptions) (result *clusterv1.LocalClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localclusteraccessesResource, localClusterAccess), &clusterv1.LocalClusterAccess{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.LocalClusterAccess), err
}

// Update takes the representation of a localClusterAccess and updates it. Returns the server's representation of the localClusterAccess, and an error, if there is any.
func (c *FakeLocalClusterAccesses) Update(ctx context.Context, localClusterAccess *clusterv1.LocalClusterAccess, opts v1.UpdateOptions) (result *clusterv1.LocalClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localclusteraccessesResource, localClusterAccess), &clusterv1.LocalClusterAccess{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.LocalClusterAccess), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalClusterAccesses) UpdateStatus(ctx context.Context, localClusterAccess *clusterv1.LocalClusterAccess, opts v1.UpdateOptions) (*clusterv1.LocalClusterAccess, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localclusteraccessesResource, "status", localClusterAccess), &clusterv1.LocalClusterAccess{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.LocalClusterAccess), err
}

// Delete takes name of the localClusterAccess and deletes it. Returns an error if one occurs.
func (c *FakeLocalClusterAccesses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(localclusteraccessesResource, name, opts), &clusterv1.LocalClusterAccess{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalClusterAccesses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localclusteraccessesResource, listOpts)

	_, err := c.Fake.Invokes(action, &clusterv1.LocalClusterAccessList{})
	return err
}

// Patch applies the patch and returns the patched localClusterAccess.
func (c *FakeLocalClusterAccesses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clusterv1.LocalClusterAccess, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localclusteraccessesResource, name, pt, data, subresources...), &clusterv1.LocalClusterAccess{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.LocalClusterAccess), err
}
