// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/agentapi/v3/pkg/client/loft/clientset_generated/clientset/typed/cluster/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClusterV1 struct {
	*testing.Fake
}

func (c *FakeClusterV1) ChartInfos() v1.ChartInfoInterface {
	return &FakeChartInfos{c}
}

func (c *FakeClusterV1) ClusterQuotas() v1.ClusterQuotaInterface {
	return &FakeClusterQuotas{c}
}

func (c *FakeClusterV1) HelmReleases(namespace string) v1.HelmReleaseInterface {
	return &FakeHelmReleases{c, namespace}
}

func (c *FakeClusterV1) LocalClusterAccesses() v1.LocalClusterAccessInterface {
	return &FakeLocalClusterAccesses{c}
}

func (c *FakeClusterV1) SleepModeConfigs(namespace string) v1.SleepModeConfigInterface {
	return &FakeSleepModeConfigs{c, namespace}
}

func (c *FakeClusterV1) Spaces() v1.SpaceInterface {
	return &FakeSpaces{c}
}

func (c *FakeClusterV1) VirtualClusters(namespace string) v1.VirtualClusterInterface {
	return &FakeVirtualClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClusterV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
