// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	clusterv1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/cluster/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFeatures implements FeatureInterface
type FakeFeatures struct {
	Fake *FakeClusterV1
}

var featuresResource = schema.GroupVersionResource{Group: "cluster.loft.sh", Version: "v1", Resource: "features"}

var featuresKind = schema.GroupVersionKind{Group: "cluster.loft.sh", Version: "v1", Kind: "Feature"}

// Get takes name of the feature, and returns the corresponding feature object, and an error if there is any.
func (c *FakeFeatures) Get(ctx context.Context, name string, options v1.GetOptions) (result *clusterv1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(featuresResource, name), &clusterv1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Feature), err
}

// List takes label and field selectors, and returns the list of Features that match those selectors.
func (c *FakeFeatures) List(ctx context.Context, opts v1.ListOptions) (result *clusterv1.FeatureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(featuresResource, featuresKind, opts), &clusterv1.FeatureList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &clusterv1.FeatureList{ListMeta: obj.(*clusterv1.FeatureList).ListMeta}
	for _, item := range obj.(*clusterv1.FeatureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested features.
func (c *FakeFeatures) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(featuresResource, opts))
}

// Create takes the representation of a feature and creates it.  Returns the server's representation of the feature, and an error, if there is any.
func (c *FakeFeatures) Create(ctx context.Context, feature *clusterv1.Feature, opts v1.CreateOptions) (result *clusterv1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(featuresResource, feature), &clusterv1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Feature), err
}

// Update takes the representation of a feature and updates it. Returns the server's representation of the feature, and an error, if there is any.
func (c *FakeFeatures) Update(ctx context.Context, feature *clusterv1.Feature, opts v1.UpdateOptions) (result *clusterv1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(featuresResource, feature), &clusterv1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Feature), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFeatures) UpdateStatus(ctx context.Context, feature *clusterv1.Feature, opts v1.UpdateOptions) (*clusterv1.Feature, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(featuresResource, "status", feature), &clusterv1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Feature), err
}

// Delete takes name of the feature and deletes it. Returns an error if one occurs.
func (c *FakeFeatures) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(featuresResource, name, opts), &clusterv1.Feature{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFeatures) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(featuresResource, listOpts)

	_, err := c.Fake.Invokes(action, &clusterv1.FeatureList{})
	return err
}

// Patch applies the patch and returns the patched feature.
func (c *FakeFeatures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *clusterv1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(featuresResource, name, pt, data, subresources...), &clusterv1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*clusterv1.Feature), err
}
