// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	storagev1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	versioned "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned"
	internalinterfaces "github.com/loft-sh/agentapi/v4/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/loft-sh/agentapi/v4/pkg/listers/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterQuotaInformer provides access to a shared informer and lister for
// ClusterQuotas.
type ClusterQuotaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ClusterQuotaLister
}

type clusterQuotaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterQuotaInformer constructs a new informer for ClusterQuota type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterQuotaInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterQuotaInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterQuotaInformer constructs a new informer for ClusterQuota type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterQuotaInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().ClusterQuotas().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().ClusterQuotas().Watch(context.TODO(), options)
			},
		},
		&storagev1.ClusterQuota{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterQuotaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterQuotaInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterQuotaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storagev1.ClusterQuota{}, f.defaultInformer)
}

func (f *clusterQuotaInformer) Lister() v1.ClusterQuotaLister {
	return v1.NewClusterQuotaLister(f.Informer().GetIndexer())
}
