// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	storagev1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	versioned "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned"
	internalinterfaces "github.com/loft-sh/agentapi/v4/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/loft-sh/agentapi/v4/pkg/listers/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualClusterInformer provides access to a shared informer and lister for
// VirtualClusters.
type VirtualClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VirtualClusterLister
}

type virtualClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVirtualClusterInformer constructs a new informer for VirtualCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualClusterInformer constructs a new informer for VirtualCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().VirtualClusters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1().VirtualClusters(namespace).Watch(context.TODO(), options)
			},
		},
		&storagev1.VirtualCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storagev1.VirtualCluster{}, f.defaultInformer)
}

func (f *virtualClusterInformer) Lister() v1.VirtualClusterLister {
	return v1.NewVirtualClusterLister(f.Informer().GetIndexer())
}
