// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	loftclusterv1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/cluster/v1"
	versioned "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned"
	internalinterfaces "github.com/loft-sh/agentapi/v4/pkg/informers/externalversions/internalinterfaces"
	clusterv1 "github.com/loft-sh/agentapi/v4/pkg/listers/cluster/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ChartInfoInformer provides access to a shared informer and lister for
// ChartInfos.
type ChartInfoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() clusterv1.ChartInfoLister
}

type chartInfoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewChartInfoInformer constructs a new informer for ChartInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewChartInfoInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredChartInfoInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredChartInfoInformer constructs a new informer for ChartInfo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredChartInfoInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1().ChartInfos().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ClusterV1().ChartInfos().Watch(context.TODO(), options)
			},
		},
		&loftclusterv1.ChartInfo{},
		resyncPeriod,
		indexers,
	)
}

func (f *chartInfoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredChartInfoInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *chartInfoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&loftclusterv1.ChartInfo{}, f.defaultInformer)
}

func (f *chartInfoInformer) Lister() clusterv1.ChartInfoLister {
	return clusterv1.NewChartInfoLister(f.Informer().GetIndexer())
}
