// Code generated by client-gen. DO NOT EDIT.

package v1

type ClusterQuotaExpansion interface{}

type LocalClusterAccessExpansion interface{}

type LocalClusterRoleTemplateExpansion interface{}

type LocalSpaceConstraintExpansion interface{}

type LocalTeamExpansion interface{}

type LocalUserExpansion interface{}

type VirtualClusterExpansion interface{}
