// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	scheme "github.com/loft-sh/agentapi/v2/pkg/client/loft/clientset_generated/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalClusterRoleTemplatesGetter has a method to return a LocalClusterRoleTemplateInterface.
// A group's client should implement this interface.
type LocalClusterRoleTemplatesGetter interface {
	LocalClusterRoleTemplates() LocalClusterRoleTemplateInterface
}

// LocalClusterRoleTemplateInterface has methods to work with LocalClusterRoleTemplate resources.
type LocalClusterRoleTemplateInterface interface {
	Create(ctx context.Context, localClusterRoleTemplate *v1.LocalClusterRoleTemplate, opts metav1.CreateOptions) (*v1.LocalClusterRoleTemplate, error)
	Update(ctx context.Context, localClusterRoleTemplate *v1.LocalClusterRoleTemplate, opts metav1.UpdateOptions) (*v1.LocalClusterRoleTemplate, error)
	UpdateStatus(ctx context.Context, localClusterRoleTemplate *v1.LocalClusterRoleTemplate, opts metav1.UpdateOptions) (*v1.LocalClusterRoleTemplate, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.LocalClusterRoleTemplate, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.LocalClusterRoleTemplateList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalClusterRoleTemplate, err error)
	LocalClusterRoleTemplateExpansion
}

// localClusterRoleTemplates implements LocalClusterRoleTemplateInterface
type localClusterRoleTemplates struct {
	client rest.Interface
}

// newLocalClusterRoleTemplates returns a LocalClusterRoleTemplates
func newLocalClusterRoleTemplates(c *StorageV1Client) *localClusterRoleTemplates {
	return &localClusterRoleTemplates{
		client: c.RESTClient(),
	}
}

// Get takes name of the localClusterRoleTemplate, and returns the corresponding localClusterRoleTemplate object, and an error if there is any.
func (c *localClusterRoleTemplates) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LocalClusterRoleTemplate, err error) {
	result = &v1.LocalClusterRoleTemplate{}
	err = c.client.Get().
		Resource("localclusterroletemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalClusterRoleTemplates that match those selectors.
func (c *localClusterRoleTemplates) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LocalClusterRoleTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.LocalClusterRoleTemplateList{}
	err = c.client.Get().
		Resource("localclusterroletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localClusterRoleTemplates.
func (c *localClusterRoleTemplates) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localclusterroletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localClusterRoleTemplate and creates it.  Returns the server's representation of the localClusterRoleTemplate, and an error, if there is any.
func (c *localClusterRoleTemplates) Create(ctx context.Context, localClusterRoleTemplate *v1.LocalClusterRoleTemplate, opts metav1.CreateOptions) (result *v1.LocalClusterRoleTemplate, err error) {
	result = &v1.LocalClusterRoleTemplate{}
	err = c.client.Post().
		Resource("localclusterroletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localClusterRoleTemplate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localClusterRoleTemplate and updates it. Returns the server's representation of the localClusterRoleTemplate, and an error, if there is any.
func (c *localClusterRoleTemplates) Update(ctx context.Context, localClusterRoleTemplate *v1.LocalClusterRoleTemplate, opts metav1.UpdateOptions) (result *v1.LocalClusterRoleTemplate, err error) {
	result = &v1.LocalClusterRoleTemplate{}
	err = c.client.Put().
		Resource("localclusterroletemplates").
		Name(localClusterRoleTemplate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localClusterRoleTemplate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localClusterRoleTemplates) UpdateStatus(ctx context.Context, localClusterRoleTemplate *v1.LocalClusterRoleTemplate, opts metav1.UpdateOptions) (result *v1.LocalClusterRoleTemplate, err error) {
	result = &v1.LocalClusterRoleTemplate{}
	err = c.client.Put().
		Resource("localclusterroletemplates").
		Name(localClusterRoleTemplate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localClusterRoleTemplate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localClusterRoleTemplate and deletes it. Returns an error if one occurs.
func (c *localClusterRoleTemplates) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localclusterroletemplates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localClusterRoleTemplates) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localclusterroletemplates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localClusterRoleTemplate.
func (c *localClusterRoleTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalClusterRoleTemplate, err error) {
	result = &v1.LocalClusterRoleTemplate{}
	err = c.client.Patch(pt).
		Resource("localclusterroletemplates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
