// Code generated by generator. DO NOT EDIT.

package loft

import (
	"github.com/loft-sh/agentapi/v3/pkg/apis/loft/cluster"
	_ "github.com/loft-sh/agentapi/v3/pkg/apis/loft/cluster/install" // Install the cluster group
	clusterv1 "github.com/loft-sh/agentapi/v3/pkg/apis/loft/cluster/v1"
	"github.com/loft-sh/apiserver/pkg/builders"
	"k8s.io/apimachinery/pkg/runtime"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		clusterv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetClusterAPIBuilder(),
	}
}

func GetClusterAPIBuilder() *builders.APIGroupBuilder {
	return builders.NewApiGroupBuilder(
		"cluster.loft.sh",
		"github.com/loft-sh/agentapi/v3/pkg/apis/loft/cluster").
		WithUnVersionedApi(cluster.ApiVersion).
		WithVersionedApis(
			clusterv1.ApiVersion,
		).
		WithRootScopedKinds(
			"ChartInfo",
			"ClusterQuota",
			"LocalClusterAccess",
			"Space",
		)
}
