// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	storagev1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterQuotaLister helps list ClusterQuotas.
// All objects returned here must be treated as read-only.
type ClusterQuotaLister interface {
	// List lists all ClusterQuotas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1.ClusterQuota, err error)
	// Get retrieves the ClusterQuota from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1.ClusterQuota, error)
	ClusterQuotaListerExpansion
}

// clusterQuotaLister implements the ClusterQuotaLister interface.
type clusterQuotaLister struct {
	listers.ResourceIndexer[*storagev1.ClusterQuota]
}

// NewClusterQuotaLister returns a new ClusterQuotaLister.
func NewClusterQuotaLister(indexer cache.Indexer) ClusterQuotaLister {
	return &clusterQuotaLister{listers.New[*storagev1.ClusterQuota](indexer, storagev1.Resource("clusterquota"))}
}
