// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalUserLister helps list LocalUsers.
// All objects returned here must be treated as read-only.
type LocalUserLister interface {
	// List lists all LocalUsers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LocalUser, err error)
	// Get retrieves the LocalUser from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.LocalUser, error)
	LocalUserListerExpansion
}

// localUserLister implements the LocalUserLister interface.
type localUserLister struct {
	indexer cache.Indexer
}

// NewLocalUserLister returns a new LocalUserLister.
func NewLocalUserLister(indexer cache.Indexer) LocalUserLister {
	return &localUserLister{indexer: indexer}
}

// List lists all LocalUsers in the indexer.
func (s *localUserLister) List(selector labels.Selector) (ret []*v1.LocalUser, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LocalUser))
	})
	return ret, err
}

// Get retrieves the LocalUser from the index for a given name.
func (s *localUserLister) Get(name string) (*v1.LocalUser, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("localuser"), name)
	}
	return obj.(*v1.LocalUser), nil
}
