// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalTeamLister helps list LocalTeams.
// All objects returned here must be treated as read-only.
type LocalTeamLister interface {
	// List lists all LocalTeams in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LocalTeam, err error)
	// Get retrieves the LocalTeam from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.LocalTeam, error)
	LocalTeamListerExpansion
}

// localTeamLister implements the LocalTeamLister interface.
type localTeamLister struct {
	indexer cache.Indexer
}

// NewLocalTeamLister returns a new LocalTeamLister.
func NewLocalTeamLister(indexer cache.Indexer) LocalTeamLister {
	return &localTeamLister{indexer: indexer}
}

// List lists all LocalTeams in the indexer.
func (s *localTeamLister) List(selector labels.Selector) (ret []*v1.LocalTeam, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LocalTeam))
	})
	return ret, err
}

// Get retrieves the LocalTeam from the index for a given name.
func (s *localTeamLister) Get(name string) (*v1.LocalTeam, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("localteam"), name)
	}
	return obj.(*v1.LocalTeam), nil
}
