// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalClusterAccessLister helps list LocalClusterAccesses.
// All objects returned here must be treated as read-only.
type LocalClusterAccessLister interface {
	// List lists all LocalClusterAccesses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.LocalClusterAccess, err error)
	// Get retrieves the LocalClusterAccess from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.LocalClusterAccess, error)
	LocalClusterAccessListerExpansion
}

// localClusterAccessLister implements the LocalClusterAccessLister interface.
type localClusterAccessLister struct {
	indexer cache.Indexer
}

// NewLocalClusterAccessLister returns a new LocalClusterAccessLister.
func NewLocalClusterAccessLister(indexer cache.Indexer) LocalClusterAccessLister {
	return &localClusterAccessLister{indexer: indexer}
}

// List lists all LocalClusterAccesses in the indexer.
func (s *localClusterAccessLister) List(selector labels.Selector) (ret []*v1.LocalClusterAccess, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.LocalClusterAccess))
	})
	return ret, err
}

// Get retrieves the LocalClusterAccess from the index for a given name.
func (s *localClusterAccessLister) Get(name string) (*v1.LocalClusterAccess, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("localclusteraccess"), name)
	}
	return obj.(*v1.LocalClusterAccess), nil
}
