// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	scheme "github.com/loft-sh/agentapi/v2/pkg/client/loft/clientset_generated/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalSpaceConstraintsGetter has a method to return a LocalSpaceConstraintInterface.
// A group's client should implement this interface.
type LocalSpaceConstraintsGetter interface {
	LocalSpaceConstraints() LocalSpaceConstraintInterface
}

// LocalSpaceConstraintInterface has methods to work with LocalSpaceConstraint resources.
type LocalSpaceConstraintInterface interface {
	Create(ctx context.Context, localSpaceConstraint *v1.LocalSpaceConstraint, opts metav1.CreateOptions) (*v1.LocalSpaceConstraint, error)
	Update(ctx context.Context, localSpaceConstraint *v1.LocalSpaceConstraint, opts metav1.UpdateOptions) (*v1.LocalSpaceConstraint, error)
	UpdateStatus(ctx context.Context, localSpaceConstraint *v1.LocalSpaceConstraint, opts metav1.UpdateOptions) (*v1.LocalSpaceConstraint, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.LocalSpaceConstraint, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.LocalSpaceConstraintList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalSpaceConstraint, err error)
	LocalSpaceConstraintExpansion
}

// localSpaceConstraints implements LocalSpaceConstraintInterface
type localSpaceConstraints struct {
	client rest.Interface
}

// newLocalSpaceConstraints returns a LocalSpaceConstraints
func newLocalSpaceConstraints(c *StorageV1Client) *localSpaceConstraints {
	return &localSpaceConstraints{
		client: c.RESTClient(),
	}
}

// Get takes name of the localSpaceConstraint, and returns the corresponding localSpaceConstraint object, and an error if there is any.
func (c *localSpaceConstraints) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LocalSpaceConstraint, err error) {
	result = &v1.LocalSpaceConstraint{}
	err = c.client.Get().
		Resource("localspaceconstraints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalSpaceConstraints that match those selectors.
func (c *localSpaceConstraints) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LocalSpaceConstraintList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.LocalSpaceConstraintList{}
	err = c.client.Get().
		Resource("localspaceconstraints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localSpaceConstraints.
func (c *localSpaceConstraints) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localspaceconstraints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localSpaceConstraint and creates it.  Returns the server's representation of the localSpaceConstraint, and an error, if there is any.
func (c *localSpaceConstraints) Create(ctx context.Context, localSpaceConstraint *v1.LocalSpaceConstraint, opts metav1.CreateOptions) (result *v1.LocalSpaceConstraint, err error) {
	result = &v1.LocalSpaceConstraint{}
	err = c.client.Post().
		Resource("localspaceconstraints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localSpaceConstraint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localSpaceConstraint and updates it. Returns the server's representation of the localSpaceConstraint, and an error, if there is any.
func (c *localSpaceConstraints) Update(ctx context.Context, localSpaceConstraint *v1.LocalSpaceConstraint, opts metav1.UpdateOptions) (result *v1.LocalSpaceConstraint, err error) {
	result = &v1.LocalSpaceConstraint{}
	err = c.client.Put().
		Resource("localspaceconstraints").
		Name(localSpaceConstraint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localSpaceConstraint).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localSpaceConstraints) UpdateStatus(ctx context.Context, localSpaceConstraint *v1.LocalSpaceConstraint, opts metav1.UpdateOptions) (result *v1.LocalSpaceConstraint, err error) {
	result = &v1.LocalSpaceConstraint{}
	err = c.client.Put().
		Resource("localspaceconstraints").
		Name(localSpaceConstraint.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localSpaceConstraint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localSpaceConstraint and deletes it. Returns an error if one occurs.
func (c *localSpaceConstraints) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localspaceconstraints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localSpaceConstraints) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localspaceconstraints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localSpaceConstraint.
func (c *localSpaceConstraints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalSpaceConstraint, err error) {
	result = &v1.LocalSpaceConstraint{}
	err = c.client.Patch(pt).
		Resource("localspaceconstraints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
