// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/loft-sh/agentapi/pkg/client/kiosk/clientset_generated/clientset/typed/config/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeConfigV1alpha1 struct {
	*testing.Fake
}

func (c *FakeConfigV1alpha1) Accounts() v1alpha1.AccountInterface {
	return &FakeAccounts{c}
}

func (c *FakeConfigV1alpha1) AccountQuotas() v1alpha1.AccountQuotaInterface {
	return &FakeAccountQuotas{c}
}

func (c *FakeConfigV1alpha1) Templates() v1alpha1.TemplateInterface {
	return &FakeTemplates{c}
}

func (c *FakeConfigV1alpha1) TemplateInstances(namespace string) v1alpha1.TemplateInstanceInterface {
	return &FakeTemplateInstances{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeConfigV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
