// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/loft-sh/agentapi/v2/pkg/apis/kiosk/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTemplates implements TemplateInterface
type FakeTemplates struct {
	Fake *FakeConfigV1alpha1
}

var templatesResource = schema.GroupVersionResource{Group: "config.kiosk.sh", Version: "v1alpha1", Resource: "templates"}

var templatesKind = schema.GroupVersionKind{Group: "config.kiosk.sh", Version: "v1alpha1", Kind: "Template"}

// Get takes name of the template, and returns the corresponding template object, and an error if there is any.
func (c *FakeTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Template, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(templatesResource, name), &v1alpha1.Template{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Template), err
}

// List takes label and field selectors, and returns the list of Templates that match those selectors.
func (c *FakeTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(templatesResource, templatesKind, opts), &v1alpha1.TemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TemplateList{ListMeta: obj.(*v1alpha1.TemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.TemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested templates.
func (c *FakeTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(templatesResource, opts))
}

// Create takes the representation of a template and creates it.  Returns the server's representation of the template, and an error, if there is any.
func (c *FakeTemplates) Create(ctx context.Context, template *v1alpha1.Template, opts v1.CreateOptions) (result *v1alpha1.Template, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(templatesResource, template), &v1alpha1.Template{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Template), err
}

// Update takes the representation of a template and updates it. Returns the server's representation of the template, and an error, if there is any.
func (c *FakeTemplates) Update(ctx context.Context, template *v1alpha1.Template, opts v1.UpdateOptions) (result *v1alpha1.Template, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(templatesResource, template), &v1alpha1.Template{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Template), err
}

// Delete takes name of the template and deletes it. Returns an error if one occurs.
func (c *FakeTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(templatesResource, name), &v1alpha1.Template{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(templatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TemplateList{})
	return err
}

// Patch applies the patch and returns the patched template.
func (c *FakeTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Template, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(templatesResource, name, pt, data, subresources...), &v1alpha1.Template{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Template), err
}
