// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned/typed/cluster/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeClusterV1 struct {
	*testing.Fake
}

func (c *FakeClusterV1) Features() v1.FeatureInterface {
	return newFakeFeatures(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeClusterV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
