// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/cluster/v1"
	clusterv1 "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned/typed/cluster/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeChartInfos implements ChartInfoInterface
type fakeChartInfos struct {
	*gentype.FakeClientWithList[*v1.ChartInfo, *v1.ChartInfoList]
	Fake *FakeClusterV1
}

func newFakeChartInfos(fake *FakeClusterV1) clusterv1.ChartInfoInterface {
	return &fakeChartInfos{
		gentype.NewFakeClientWithList[*v1.ChartInfo, *v1.ChartInfoList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("chartinfos"),
			v1.SchemeGroupVersion.WithKind("ChartInfo"),
			func() *v1.ChartInfo { return &v1.ChartInfo{} },
			func() *v1.ChartInfoList { return &v1.ChartInfoList{} },
			func(dst, src *v1.ChartInfoList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ChartInfoList) []*v1.ChartInfo { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ChartInfoList, items []*v1.ChartInfo) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
