// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/cluster/v1"
	clusterv1 "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned/typed/cluster/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHelmReleases implements HelmReleaseInterface
type fakeHelmReleases struct {
	*gentype.FakeClientWithList[*v1.HelmRelease, *v1.HelmReleaseList]
	Fake *FakeClusterV1
}

func newFakeHelmReleases(fake *FakeClusterV1, namespace string) clusterv1.HelmReleaseInterface {
	return &fakeHelmReleases{
		gentype.NewFakeClientWithList[*v1.HelmRelease, *v1.HelmReleaseList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("helmreleases"),
			v1.SchemeGroupVersion.WithKind("HelmRelease"),
			func() *v1.HelmRelease { return &v1.HelmRelease{} },
			func() *v1.HelmReleaseList { return &v1.HelmReleaseList{} },
			func(dst, src *v1.HelmReleaseList) { dst.ListMeta = src.ListMeta },
			func(list *v1.HelmReleaseList) []*v1.HelmRelease { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.HelmReleaseList, items []*v1.HelmRelease) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
