// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/loft-sh/agentapi/pkg/client/kiosk/clientset_generated/clientset/typed/tenancy/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTenancyV1alpha1 struct {
	*testing.Fake
}

func (c *FakeTenancyV1alpha1) Accounts() v1alpha1.AccountInterface {
	return &FakeAccounts{c}
}

func (c *FakeTenancyV1alpha1) Spaces() v1alpha1.SpaceInterface {
	return &FakeSpaces{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTenancyV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
