// Code generated by generator. DO NOT EDIT.

package devsy

import (
	"github.com/skevetter/agentapi/pkg/apis/devsy/cluster"
	_ "github.com/skevetter/agentapi/pkg/apis/devsy/cluster/install" // Install the cluster group
	clusterv1 "github.com/skevetter/agentapi/pkg/apis/devsy/cluster/v1"
	"github.com/skevetter/apiserver/pkg/builders"
	"k8s.io/apimachinery/pkg/runtime"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		clusterv1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetClusterAPIBuilder(),
	}
}

func GetClusterAPIBuilder() *builders.APIGroupBuilder {
	return builders.NewApiGroupBuilder(
		"cluster.devsy.sh",
		"github.com/skevetter/agentapi/pkg/apis/devsy/cluster").
		WithUnVersionedApi(cluster.ApiVersion).
		WithVersionedApis(
			clusterv1.ApiVersion,
		).
		WithRootScopedKinds(
			"ChartInfo",
			"Feature",
		)
}
