// Code generated by generator. DO NOT EDIT.

package kiosk

import (
	"github.com/loft-sh/agentapi/pkg/apis/kiosk/tenancy"
	_ "github.com/loft-sh/agentapi/pkg/apis/kiosk/tenancy/install" // Install the tenancy group
	tenancyv1alpha1 "github.com/loft-sh/agentapi/pkg/apis/kiosk/tenancy/v1alpha1"
	"github.com/loft-sh/apiserver/pkg/builders"
	"k8s.io/apimachinery/pkg/runtime"
)

var (
	localSchemeBuilder = runtime.SchemeBuilder{
		tenancyv1alpha1.AddToScheme,
	}
	AddToScheme = localSchemeBuilder.AddToScheme
)

// GetAllApiBuilders returns all known APIGroupBuilders
// so they can be registered with the apiserver
func GetAllApiBuilders() []*builders.APIGroupBuilder {
	return []*builders.APIGroupBuilder{
		GetTenancyAPIBuilder(),
	}
}

var tenancyApiGroup = builders.NewApiGroupBuilder(
	"tenancy.kiosk.sh",
	"github.com/loft-sh/agentapi/pkg/apis/kiosk/tenancy").
	WithUnVersionedApi(tenancy.ApiVersion).
	WithVersionedApis(
		tenancyv1alpha1.ApiVersion,
	).
	WithRootScopedKinds(
		"Account",
		"Space",
	)

func GetTenancyAPIBuilder() *builders.APIGroupBuilder {
	return tenancyApiGroup
}
