// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AccountExpansion interface{}

type AccountQuotaExpansion interface{}

type TemplateExpansion interface{}

type TemplateInstanceExpansion interface{}
