// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	cluster "github.com/loft-sh/agentapi/pkg/apis/loft/cluster"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Account)(nil), (*cluster.Account)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Account_To_cluster_Account(a.(*Account), b.(*cluster.Account), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.Account)(nil), (*Account)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_Account_To_v1_Account(a.(*cluster.Account), b.(*Account), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccountClusterRoles)(nil), (*cluster.AccountClusterRoles)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccountClusterRoles_To_cluster_AccountClusterRoles(a.(*AccountClusterRoles), b.(*cluster.AccountClusterRoles), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.AccountClusterRoles)(nil), (*AccountClusterRoles)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_AccountClusterRoles_To_v1_AccountClusterRoles(a.(*cluster.AccountClusterRoles), b.(*AccountClusterRoles), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccountClusterRolesList)(nil), (*cluster.AccountClusterRolesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccountClusterRolesList_To_cluster_AccountClusterRolesList(a.(*AccountClusterRolesList), b.(*cluster.AccountClusterRolesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.AccountClusterRolesList)(nil), (*AccountClusterRolesList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_AccountClusterRolesList_To_v1_AccountClusterRolesList(a.(*cluster.AccountClusterRolesList), b.(*AccountClusterRolesList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccountList)(nil), (*cluster.AccountList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccountList_To_cluster_AccountList(a.(*AccountList), b.(*cluster.AccountList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.AccountList)(nil), (*AccountList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_AccountList_To_v1_AccountList(a.(*cluster.AccountList), b.(*AccountList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccountSpec)(nil), (*cluster.AccountSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccountSpec_To_cluster_AccountSpec(a.(*AccountSpec), b.(*cluster.AccountSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.AccountSpec)(nil), (*AccountSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_AccountSpec_To_v1_AccountSpec(a.(*cluster.AccountSpec), b.(*AccountSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccountStatus)(nil), (*cluster.AccountStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccountStatus_To_cluster_AccountStatus(a.(*AccountStatus), b.(*cluster.AccountStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.AccountStatus)(nil), (*AccountStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_AccountStatus_To_v1_AccountStatus(a.(*cluster.AccountStatus), b.(*AccountStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Chart)(nil), (*cluster.Chart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Chart_To_cluster_Chart(a.(*Chart), b.(*cluster.Chart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.Chart)(nil), (*Chart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_Chart_To_v1_Chart(a.(*cluster.Chart), b.(*Chart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EpochInfo)(nil), (*cluster.EpochInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_EpochInfo_To_cluster_EpochInfo(a.(*EpochInfo), b.(*cluster.EpochInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.EpochInfo)(nil), (*EpochInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_EpochInfo_To_v1_EpochInfo(a.(*cluster.EpochInfo), b.(*EpochInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmRelease)(nil), (*cluster.HelmRelease)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HelmRelease_To_cluster_HelmRelease(a.(*HelmRelease), b.(*cluster.HelmRelease), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.HelmRelease)(nil), (*HelmRelease)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_HelmRelease_To_v1_HelmRelease(a.(*cluster.HelmRelease), b.(*HelmRelease), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmReleaseList)(nil), (*cluster.HelmReleaseList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HelmReleaseList_To_cluster_HelmReleaseList(a.(*HelmReleaseList), b.(*cluster.HelmReleaseList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.HelmReleaseList)(nil), (*HelmReleaseList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_HelmReleaseList_To_v1_HelmReleaseList(a.(*cluster.HelmReleaseList), b.(*HelmReleaseList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmReleaseRollback)(nil), (*cluster.HelmReleaseRollback)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HelmReleaseRollback_To_cluster_HelmReleaseRollback(a.(*HelmReleaseRollback), b.(*cluster.HelmReleaseRollback), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.HelmReleaseRollback)(nil), (*HelmReleaseRollback)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_HelmReleaseRollback_To_v1_HelmReleaseRollback(a.(*cluster.HelmReleaseRollback), b.(*HelmReleaseRollback), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmReleaseRollbackList)(nil), (*cluster.HelmReleaseRollbackList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HelmReleaseRollbackList_To_cluster_HelmReleaseRollbackList(a.(*HelmReleaseRollbackList), b.(*cluster.HelmReleaseRollbackList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.HelmReleaseRollbackList)(nil), (*HelmReleaseRollbackList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_HelmReleaseRollbackList_To_v1_HelmReleaseRollbackList(a.(*cluster.HelmReleaseRollbackList), b.(*HelmReleaseRollbackList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmReleaseSpec)(nil), (*cluster.HelmReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HelmReleaseSpec_To_cluster_HelmReleaseSpec(a.(*HelmReleaseSpec), b.(*cluster.HelmReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.HelmReleaseSpec)(nil), (*HelmReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_HelmReleaseSpec_To_v1_HelmReleaseSpec(a.(*cluster.HelmReleaseSpec), b.(*HelmReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HelmReleaseStatus)(nil), (*cluster.HelmReleaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_HelmReleaseStatus_To_cluster_HelmReleaseStatus(a.(*HelmReleaseStatus), b.(*cluster.HelmReleaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.HelmReleaseStatus)(nil), (*HelmReleaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_HelmReleaseStatus_To_v1_HelmReleaseStatus(a.(*cluster.HelmReleaseStatus), b.(*HelmReleaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Info)(nil), (*cluster.Info)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Info_To_cluster_Info(a.(*Info), b.(*cluster.Info), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.Info)(nil), (*Info)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_Info_To_v1_Info(a.(*cluster.Info), b.(*Info), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Maintainer)(nil), (*cluster.Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Maintainer_To_cluster_Maintainer(a.(*Maintainer), b.(*cluster.Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.Maintainer)(nil), (*Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_Maintainer_To_v1_Maintainer(a.(*cluster.Maintainer), b.(*Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Metadata)(nil), (*cluster.Metadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Metadata_To_cluster_Metadata(a.(*Metadata), b.(*cluster.Metadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.Metadata)(nil), (*Metadata)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_Metadata_To_v1_Metadata(a.(*cluster.Metadata), b.(*Metadata), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SleepModeConfig)(nil), (*cluster.SleepModeConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SleepModeConfig_To_cluster_SleepModeConfig(a.(*SleepModeConfig), b.(*cluster.SleepModeConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.SleepModeConfig)(nil), (*SleepModeConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_SleepModeConfig_To_v1_SleepModeConfig(a.(*cluster.SleepModeConfig), b.(*SleepModeConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SleepModeConfigList)(nil), (*cluster.SleepModeConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SleepModeConfigList_To_cluster_SleepModeConfigList(a.(*SleepModeConfigList), b.(*cluster.SleepModeConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.SleepModeConfigList)(nil), (*SleepModeConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_SleepModeConfigList_To_v1_SleepModeConfigList(a.(*cluster.SleepModeConfigList), b.(*SleepModeConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SleepModeConfigSpec)(nil), (*cluster.SleepModeConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SleepModeConfigSpec_To_cluster_SleepModeConfigSpec(a.(*SleepModeConfigSpec), b.(*cluster.SleepModeConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.SleepModeConfigSpec)(nil), (*SleepModeConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_SleepModeConfigSpec_To_v1_SleepModeConfigSpec(a.(*cluster.SleepModeConfigSpec), b.(*SleepModeConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SleepModeConfigStatus)(nil), (*cluster.SleepModeConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SleepModeConfigStatus_To_cluster_SleepModeConfigStatus(a.(*SleepModeConfigStatus), b.(*cluster.SleepModeConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.SleepModeConfigStatus)(nil), (*SleepModeConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_SleepModeConfigStatus_To_v1_SleepModeConfigStatus(a.(*cluster.SleepModeConfigStatus), b.(*SleepModeConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualCluster)(nil), (*cluster.VirtualCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualCluster_To_cluster_VirtualCluster(a.(*VirtualCluster), b.(*cluster.VirtualCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.VirtualCluster)(nil), (*VirtualCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_VirtualCluster_To_v1_VirtualCluster(a.(*cluster.VirtualCluster), b.(*VirtualCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualClusterList)(nil), (*cluster.VirtualClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualClusterList_To_cluster_VirtualClusterList(a.(*VirtualClusterList), b.(*cluster.VirtualClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.VirtualClusterList)(nil), (*VirtualClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_VirtualClusterList_To_v1_VirtualClusterList(a.(*cluster.VirtualClusterList), b.(*VirtualClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualClusterSpec)(nil), (*cluster.VirtualClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualClusterSpec_To_cluster_VirtualClusterSpec(a.(*VirtualClusterSpec), b.(*cluster.VirtualClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.VirtualClusterSpec)(nil), (*VirtualClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_VirtualClusterSpec_To_v1_VirtualClusterSpec(a.(*cluster.VirtualClusterSpec), b.(*VirtualClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualClusterStatus)(nil), (*cluster.VirtualClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualClusterStatus_To_cluster_VirtualClusterStatus(a.(*VirtualClusterStatus), b.(*cluster.VirtualClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.VirtualClusterStatus)(nil), (*VirtualClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_VirtualClusterStatus_To_v1_VirtualClusterStatus(a.(*cluster.VirtualClusterStatus), b.(*VirtualClusterStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Account_To_cluster_Account(in *Account, out *cluster.Account, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_AccountSpec_To_cluster_AccountSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_AccountStatus_To_cluster_AccountStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Account_To_cluster_Account is an autogenerated conversion function.
func Convert_v1_Account_To_cluster_Account(in *Account, out *cluster.Account, s conversion.Scope) error {
	return autoConvert_v1_Account_To_cluster_Account(in, out, s)
}

func autoConvert_cluster_Account_To_v1_Account(in *cluster.Account, out *Account, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cluster_AccountSpec_To_v1_AccountSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cluster_AccountStatus_To_v1_AccountStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cluster_Account_To_v1_Account is an autogenerated conversion function.
func Convert_cluster_Account_To_v1_Account(in *cluster.Account, out *Account, s conversion.Scope) error {
	return autoConvert_cluster_Account_To_v1_Account(in, out, s)
}

func autoConvert_v1_AccountClusterRoles_To_cluster_AccountClusterRoles(in *AccountClusterRoles, out *cluster.AccountClusterRoles, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClusterRoles = *(*[]string)(unsafe.Pointer(&in.ClusterRoles))
	return nil
}

// Convert_v1_AccountClusterRoles_To_cluster_AccountClusterRoles is an autogenerated conversion function.
func Convert_v1_AccountClusterRoles_To_cluster_AccountClusterRoles(in *AccountClusterRoles, out *cluster.AccountClusterRoles, s conversion.Scope) error {
	return autoConvert_v1_AccountClusterRoles_To_cluster_AccountClusterRoles(in, out, s)
}

func autoConvert_cluster_AccountClusterRoles_To_v1_AccountClusterRoles(in *cluster.AccountClusterRoles, out *AccountClusterRoles, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClusterRoles = *(*[]string)(unsafe.Pointer(&in.ClusterRoles))
	return nil
}

// Convert_cluster_AccountClusterRoles_To_v1_AccountClusterRoles is an autogenerated conversion function.
func Convert_cluster_AccountClusterRoles_To_v1_AccountClusterRoles(in *cluster.AccountClusterRoles, out *AccountClusterRoles, s conversion.Scope) error {
	return autoConvert_cluster_AccountClusterRoles_To_v1_AccountClusterRoles(in, out, s)
}

func autoConvert_v1_AccountClusterRolesList_To_cluster_AccountClusterRolesList(in *AccountClusterRolesList, out *cluster.AccountClusterRolesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.AccountClusterRoles)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AccountClusterRolesList_To_cluster_AccountClusterRolesList is an autogenerated conversion function.
func Convert_v1_AccountClusterRolesList_To_cluster_AccountClusterRolesList(in *AccountClusterRolesList, out *cluster.AccountClusterRolesList, s conversion.Scope) error {
	return autoConvert_v1_AccountClusterRolesList_To_cluster_AccountClusterRolesList(in, out, s)
}

func autoConvert_cluster_AccountClusterRolesList_To_v1_AccountClusterRolesList(in *cluster.AccountClusterRolesList, out *AccountClusterRolesList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AccountClusterRoles)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_AccountClusterRolesList_To_v1_AccountClusterRolesList is an autogenerated conversion function.
func Convert_cluster_AccountClusterRolesList_To_v1_AccountClusterRolesList(in *cluster.AccountClusterRolesList, out *AccountClusterRolesList, s conversion.Scope) error {
	return autoConvert_cluster_AccountClusterRolesList_To_v1_AccountClusterRolesList(in, out, s)
}

func autoConvert_v1_AccountList_To_cluster_AccountList(in *AccountList, out *cluster.AccountList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.Account)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AccountList_To_cluster_AccountList is an autogenerated conversion function.
func Convert_v1_AccountList_To_cluster_AccountList(in *AccountList, out *cluster.AccountList, s conversion.Scope) error {
	return autoConvert_v1_AccountList_To_cluster_AccountList(in, out, s)
}

func autoConvert_cluster_AccountList_To_v1_AccountList(in *cluster.AccountList, out *AccountList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Account)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_AccountList_To_v1_AccountList is an autogenerated conversion function.
func Convert_cluster_AccountList_To_v1_AccountList(in *cluster.AccountList, out *AccountList, s conversion.Scope) error {
	return autoConvert_cluster_AccountList_To_v1_AccountList(in, out, s)
}

func autoConvert_v1_AccountSpec_To_cluster_AccountSpec(in *AccountSpec, out *cluster.AccountSpec, s conversion.Scope) error {
	out.AccountSpec = in.AccountSpec
	return nil
}

// Convert_v1_AccountSpec_To_cluster_AccountSpec is an autogenerated conversion function.
func Convert_v1_AccountSpec_To_cluster_AccountSpec(in *AccountSpec, out *cluster.AccountSpec, s conversion.Scope) error {
	return autoConvert_v1_AccountSpec_To_cluster_AccountSpec(in, out, s)
}

func autoConvert_cluster_AccountSpec_To_v1_AccountSpec(in *cluster.AccountSpec, out *AccountSpec, s conversion.Scope) error {
	out.AccountSpec = in.AccountSpec
	return nil
}

// Convert_cluster_AccountSpec_To_v1_AccountSpec is an autogenerated conversion function.
func Convert_cluster_AccountSpec_To_v1_AccountSpec(in *cluster.AccountSpec, out *AccountSpec, s conversion.Scope) error {
	return autoConvert_cluster_AccountSpec_To_v1_AccountSpec(in, out, s)
}

func autoConvert_v1_AccountStatus_To_cluster_AccountStatus(in *AccountStatus, out *cluster.AccountStatus, s conversion.Scope) error {
	out.AccountStatus = in.AccountStatus
	return nil
}

// Convert_v1_AccountStatus_To_cluster_AccountStatus is an autogenerated conversion function.
func Convert_v1_AccountStatus_To_cluster_AccountStatus(in *AccountStatus, out *cluster.AccountStatus, s conversion.Scope) error {
	return autoConvert_v1_AccountStatus_To_cluster_AccountStatus(in, out, s)
}

func autoConvert_cluster_AccountStatus_To_v1_AccountStatus(in *cluster.AccountStatus, out *AccountStatus, s conversion.Scope) error {
	out.AccountStatus = in.AccountStatus
	return nil
}

// Convert_cluster_AccountStatus_To_v1_AccountStatus is an autogenerated conversion function.
func Convert_cluster_AccountStatus_To_v1_AccountStatus(in *cluster.AccountStatus, out *AccountStatus, s conversion.Scope) error {
	return autoConvert_cluster_AccountStatus_To_v1_AccountStatus(in, out, s)
}

func autoConvert_v1_Chart_To_cluster_Chart(in *Chart, out *cluster.Chart, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.RepoURL = in.RepoURL
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v1_Chart_To_cluster_Chart is an autogenerated conversion function.
func Convert_v1_Chart_To_cluster_Chart(in *Chart, out *cluster.Chart, s conversion.Scope) error {
	return autoConvert_v1_Chart_To_cluster_Chart(in, out, s)
}

func autoConvert_cluster_Chart_To_v1_Chart(in *cluster.Chart, out *Chart, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.RepoURL = in.RepoURL
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_cluster_Chart_To_v1_Chart is an autogenerated conversion function.
func Convert_cluster_Chart_To_v1_Chart(in *cluster.Chart, out *Chart, s conversion.Scope) error {
	return autoConvert_cluster_Chart_To_v1_Chart(in, out, s)
}

func autoConvert_v1_EpochInfo_To_cluster_EpochInfo(in *EpochInfo, out *cluster.EpochInfo, s conversion.Scope) error {
	out.Start = in.Start
	out.Slept = in.Slept
	return nil
}

// Convert_v1_EpochInfo_To_cluster_EpochInfo is an autogenerated conversion function.
func Convert_v1_EpochInfo_To_cluster_EpochInfo(in *EpochInfo, out *cluster.EpochInfo, s conversion.Scope) error {
	return autoConvert_v1_EpochInfo_To_cluster_EpochInfo(in, out, s)
}

func autoConvert_cluster_EpochInfo_To_v1_EpochInfo(in *cluster.EpochInfo, out *EpochInfo, s conversion.Scope) error {
	out.Start = in.Start
	out.Slept = in.Slept
	return nil
}

// Convert_cluster_EpochInfo_To_v1_EpochInfo is an autogenerated conversion function.
func Convert_cluster_EpochInfo_To_v1_EpochInfo(in *cluster.EpochInfo, out *EpochInfo, s conversion.Scope) error {
	return autoConvert_cluster_EpochInfo_To_v1_EpochInfo(in, out, s)
}

func autoConvert_v1_HelmRelease_To_cluster_HelmRelease(in *HelmRelease, out *cluster.HelmRelease, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_HelmReleaseSpec_To_cluster_HelmReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_HelmReleaseStatus_To_cluster_HelmReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_HelmRelease_To_cluster_HelmRelease is an autogenerated conversion function.
func Convert_v1_HelmRelease_To_cluster_HelmRelease(in *HelmRelease, out *cluster.HelmRelease, s conversion.Scope) error {
	return autoConvert_v1_HelmRelease_To_cluster_HelmRelease(in, out, s)
}

func autoConvert_cluster_HelmRelease_To_v1_HelmRelease(in *cluster.HelmRelease, out *HelmRelease, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cluster_HelmReleaseSpec_To_v1_HelmReleaseSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cluster_HelmReleaseStatus_To_v1_HelmReleaseStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cluster_HelmRelease_To_v1_HelmRelease is an autogenerated conversion function.
func Convert_cluster_HelmRelease_To_v1_HelmRelease(in *cluster.HelmRelease, out *HelmRelease, s conversion.Scope) error {
	return autoConvert_cluster_HelmRelease_To_v1_HelmRelease(in, out, s)
}

func autoConvert_v1_HelmReleaseList_To_cluster_HelmReleaseList(in *HelmReleaseList, out *cluster.HelmReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.HelmRelease)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_HelmReleaseList_To_cluster_HelmReleaseList is an autogenerated conversion function.
func Convert_v1_HelmReleaseList_To_cluster_HelmReleaseList(in *HelmReleaseList, out *cluster.HelmReleaseList, s conversion.Scope) error {
	return autoConvert_v1_HelmReleaseList_To_cluster_HelmReleaseList(in, out, s)
}

func autoConvert_cluster_HelmReleaseList_To_v1_HelmReleaseList(in *cluster.HelmReleaseList, out *HelmReleaseList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HelmRelease)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_HelmReleaseList_To_v1_HelmReleaseList is an autogenerated conversion function.
func Convert_cluster_HelmReleaseList_To_v1_HelmReleaseList(in *cluster.HelmReleaseList, out *HelmReleaseList, s conversion.Scope) error {
	return autoConvert_cluster_HelmReleaseList_To_v1_HelmReleaseList(in, out, s)
}

func autoConvert_v1_HelmReleaseRollback_To_cluster_HelmReleaseRollback(in *HelmReleaseRollback, out *cluster.HelmReleaseRollback, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Revision = in.Revision
	return nil
}

// Convert_v1_HelmReleaseRollback_To_cluster_HelmReleaseRollback is an autogenerated conversion function.
func Convert_v1_HelmReleaseRollback_To_cluster_HelmReleaseRollback(in *HelmReleaseRollback, out *cluster.HelmReleaseRollback, s conversion.Scope) error {
	return autoConvert_v1_HelmReleaseRollback_To_cluster_HelmReleaseRollback(in, out, s)
}

func autoConvert_cluster_HelmReleaseRollback_To_v1_HelmReleaseRollback(in *cluster.HelmReleaseRollback, out *HelmReleaseRollback, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Revision = in.Revision
	return nil
}

// Convert_cluster_HelmReleaseRollback_To_v1_HelmReleaseRollback is an autogenerated conversion function.
func Convert_cluster_HelmReleaseRollback_To_v1_HelmReleaseRollback(in *cluster.HelmReleaseRollback, out *HelmReleaseRollback, s conversion.Scope) error {
	return autoConvert_cluster_HelmReleaseRollback_To_v1_HelmReleaseRollback(in, out, s)
}

func autoConvert_v1_HelmReleaseRollbackList_To_cluster_HelmReleaseRollbackList(in *HelmReleaseRollbackList, out *cluster.HelmReleaseRollbackList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.HelmReleaseRollback)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_HelmReleaseRollbackList_To_cluster_HelmReleaseRollbackList is an autogenerated conversion function.
func Convert_v1_HelmReleaseRollbackList_To_cluster_HelmReleaseRollbackList(in *HelmReleaseRollbackList, out *cluster.HelmReleaseRollbackList, s conversion.Scope) error {
	return autoConvert_v1_HelmReleaseRollbackList_To_cluster_HelmReleaseRollbackList(in, out, s)
}

func autoConvert_cluster_HelmReleaseRollbackList_To_v1_HelmReleaseRollbackList(in *cluster.HelmReleaseRollbackList, out *HelmReleaseRollbackList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]HelmReleaseRollback)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_HelmReleaseRollbackList_To_v1_HelmReleaseRollbackList is an autogenerated conversion function.
func Convert_cluster_HelmReleaseRollbackList_To_v1_HelmReleaseRollbackList(in *cluster.HelmReleaseRollbackList, out *HelmReleaseRollbackList, s conversion.Scope) error {
	return autoConvert_cluster_HelmReleaseRollbackList_To_v1_HelmReleaseRollbackList(in, out, s)
}

func autoConvert_v1_HelmReleaseSpec_To_cluster_HelmReleaseSpec(in *HelmReleaseSpec, out *cluster.HelmReleaseSpec, s conversion.Scope) error {
	if err := Convert_v1_Chart_To_cluster_Chart(&in.Chart, &out.Chart, s); err != nil {
		return err
	}
	out.Manifests = in.Manifests
	out.Config = in.Config
	out.InsecureSkipTlsVerify = in.InsecureSkipTlsVerify
	return nil
}

// Convert_v1_HelmReleaseSpec_To_cluster_HelmReleaseSpec is an autogenerated conversion function.
func Convert_v1_HelmReleaseSpec_To_cluster_HelmReleaseSpec(in *HelmReleaseSpec, out *cluster.HelmReleaseSpec, s conversion.Scope) error {
	return autoConvert_v1_HelmReleaseSpec_To_cluster_HelmReleaseSpec(in, out, s)
}

func autoConvert_cluster_HelmReleaseSpec_To_v1_HelmReleaseSpec(in *cluster.HelmReleaseSpec, out *HelmReleaseSpec, s conversion.Scope) error {
	if err := Convert_cluster_Chart_To_v1_Chart(&in.Chart, &out.Chart, s); err != nil {
		return err
	}
	out.Manifests = in.Manifests
	out.Config = in.Config
	out.InsecureSkipTlsVerify = in.InsecureSkipTlsVerify
	return nil
}

// Convert_cluster_HelmReleaseSpec_To_v1_HelmReleaseSpec is an autogenerated conversion function.
func Convert_cluster_HelmReleaseSpec_To_v1_HelmReleaseSpec(in *cluster.HelmReleaseSpec, out *HelmReleaseSpec, s conversion.Scope) error {
	return autoConvert_cluster_HelmReleaseSpec_To_v1_HelmReleaseSpec(in, out, s)
}

func autoConvert_v1_HelmReleaseStatus_To_cluster_HelmReleaseStatus(in *HelmReleaseStatus, out *cluster.HelmReleaseStatus, s conversion.Scope) error {
	out.Revision = in.Revision
	out.Info = (*cluster.Info)(unsafe.Pointer(in.Info))
	out.Metadata = (*cluster.Metadata)(unsafe.Pointer(in.Metadata))
	return nil
}

// Convert_v1_HelmReleaseStatus_To_cluster_HelmReleaseStatus is an autogenerated conversion function.
func Convert_v1_HelmReleaseStatus_To_cluster_HelmReleaseStatus(in *HelmReleaseStatus, out *cluster.HelmReleaseStatus, s conversion.Scope) error {
	return autoConvert_v1_HelmReleaseStatus_To_cluster_HelmReleaseStatus(in, out, s)
}

func autoConvert_cluster_HelmReleaseStatus_To_v1_HelmReleaseStatus(in *cluster.HelmReleaseStatus, out *HelmReleaseStatus, s conversion.Scope) error {
	out.Revision = in.Revision
	out.Info = (*Info)(unsafe.Pointer(in.Info))
	out.Metadata = (*Metadata)(unsafe.Pointer(in.Metadata))
	return nil
}

// Convert_cluster_HelmReleaseStatus_To_v1_HelmReleaseStatus is an autogenerated conversion function.
func Convert_cluster_HelmReleaseStatus_To_v1_HelmReleaseStatus(in *cluster.HelmReleaseStatus, out *HelmReleaseStatus, s conversion.Scope) error {
	return autoConvert_cluster_HelmReleaseStatus_To_v1_HelmReleaseStatus(in, out, s)
}

func autoConvert_v1_Info_To_cluster_Info(in *Info, out *cluster.Info, s conversion.Scope) error {
	out.FirstDeployed = in.FirstDeployed
	out.LastDeployed = in.LastDeployed
	out.Deleted = in.Deleted
	out.Description = in.Description
	out.Status = cluster.Status(in.Status)
	out.Notes = in.Notes
	return nil
}

// Convert_v1_Info_To_cluster_Info is an autogenerated conversion function.
func Convert_v1_Info_To_cluster_Info(in *Info, out *cluster.Info, s conversion.Scope) error {
	return autoConvert_v1_Info_To_cluster_Info(in, out, s)
}

func autoConvert_cluster_Info_To_v1_Info(in *cluster.Info, out *Info, s conversion.Scope) error {
	out.FirstDeployed = in.FirstDeployed
	out.LastDeployed = in.LastDeployed
	out.Deleted = in.Deleted
	out.Description = in.Description
	out.Status = Status(in.Status)
	out.Notes = in.Notes
	return nil
}

// Convert_cluster_Info_To_v1_Info is an autogenerated conversion function.
func Convert_cluster_Info_To_v1_Info(in *cluster.Info, out *Info, s conversion.Scope) error {
	return autoConvert_cluster_Info_To_v1_Info(in, out, s)
}

func autoConvert_v1_Maintainer_To_cluster_Maintainer(in *Maintainer, out *cluster.Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Email = in.Email
	out.URL = in.URL
	return nil
}

// Convert_v1_Maintainer_To_cluster_Maintainer is an autogenerated conversion function.
func Convert_v1_Maintainer_To_cluster_Maintainer(in *Maintainer, out *cluster.Maintainer, s conversion.Scope) error {
	return autoConvert_v1_Maintainer_To_cluster_Maintainer(in, out, s)
}

func autoConvert_cluster_Maintainer_To_v1_Maintainer(in *cluster.Maintainer, out *Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Email = in.Email
	out.URL = in.URL
	return nil
}

// Convert_cluster_Maintainer_To_v1_Maintainer is an autogenerated conversion function.
func Convert_cluster_Maintainer_To_v1_Maintainer(in *cluster.Maintainer, out *Maintainer, s conversion.Scope) error {
	return autoConvert_cluster_Maintainer_To_v1_Maintainer(in, out, s)
}

func autoConvert_v1_Metadata_To_cluster_Metadata(in *Metadata, out *cluster.Metadata, s conversion.Scope) error {
	out.Name = in.Name
	out.Home = in.Home
	out.Sources = *(*[]string)(unsafe.Pointer(&in.Sources))
	out.Version = in.Version
	out.Description = in.Description
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Maintainers = *(*[]*cluster.Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.Icon = in.Icon
	out.APIVersion = in.APIVersion
	out.Condition = in.Condition
	out.Tags = in.Tags
	out.AppVersion = in.AppVersion
	out.Deprecated = in.Deprecated
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.KubeVersion = in.KubeVersion
	out.Type = in.Type
	return nil
}

// Convert_v1_Metadata_To_cluster_Metadata is an autogenerated conversion function.
func Convert_v1_Metadata_To_cluster_Metadata(in *Metadata, out *cluster.Metadata, s conversion.Scope) error {
	return autoConvert_v1_Metadata_To_cluster_Metadata(in, out, s)
}

func autoConvert_cluster_Metadata_To_v1_Metadata(in *cluster.Metadata, out *Metadata, s conversion.Scope) error {
	out.Name = in.Name
	out.Home = in.Home
	out.Sources = *(*[]string)(unsafe.Pointer(&in.Sources))
	out.Version = in.Version
	out.Description = in.Description
	out.Keywords = *(*[]string)(unsafe.Pointer(&in.Keywords))
	out.Maintainers = *(*[]*Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.Icon = in.Icon
	out.APIVersion = in.APIVersion
	out.Condition = in.Condition
	out.Tags = in.Tags
	out.AppVersion = in.AppVersion
	out.Deprecated = in.Deprecated
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.KubeVersion = in.KubeVersion
	out.Type = in.Type
	return nil
}

// Convert_cluster_Metadata_To_v1_Metadata is an autogenerated conversion function.
func Convert_cluster_Metadata_To_v1_Metadata(in *cluster.Metadata, out *Metadata, s conversion.Scope) error {
	return autoConvert_cluster_Metadata_To_v1_Metadata(in, out, s)
}

func autoConvert_v1_SleepModeConfig_To_cluster_SleepModeConfig(in *SleepModeConfig, out *cluster.SleepModeConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SleepModeConfigSpec_To_cluster_SleepModeConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_SleepModeConfigStatus_To_cluster_SleepModeConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_SleepModeConfig_To_cluster_SleepModeConfig is an autogenerated conversion function.
func Convert_v1_SleepModeConfig_To_cluster_SleepModeConfig(in *SleepModeConfig, out *cluster.SleepModeConfig, s conversion.Scope) error {
	return autoConvert_v1_SleepModeConfig_To_cluster_SleepModeConfig(in, out, s)
}

func autoConvert_cluster_SleepModeConfig_To_v1_SleepModeConfig(in *cluster.SleepModeConfig, out *SleepModeConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cluster_SleepModeConfigSpec_To_v1_SleepModeConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cluster_SleepModeConfigStatus_To_v1_SleepModeConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cluster_SleepModeConfig_To_v1_SleepModeConfig is an autogenerated conversion function.
func Convert_cluster_SleepModeConfig_To_v1_SleepModeConfig(in *cluster.SleepModeConfig, out *SleepModeConfig, s conversion.Scope) error {
	return autoConvert_cluster_SleepModeConfig_To_v1_SleepModeConfig(in, out, s)
}

func autoConvert_v1_SleepModeConfigList_To_cluster_SleepModeConfigList(in *SleepModeConfigList, out *cluster.SleepModeConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.SleepModeConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_SleepModeConfigList_To_cluster_SleepModeConfigList is an autogenerated conversion function.
func Convert_v1_SleepModeConfigList_To_cluster_SleepModeConfigList(in *SleepModeConfigList, out *cluster.SleepModeConfigList, s conversion.Scope) error {
	return autoConvert_v1_SleepModeConfigList_To_cluster_SleepModeConfigList(in, out, s)
}

func autoConvert_cluster_SleepModeConfigList_To_v1_SleepModeConfigList(in *cluster.SleepModeConfigList, out *SleepModeConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]SleepModeConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_SleepModeConfigList_To_v1_SleepModeConfigList is an autogenerated conversion function.
func Convert_cluster_SleepModeConfigList_To_v1_SleepModeConfigList(in *cluster.SleepModeConfigList, out *SleepModeConfigList, s conversion.Scope) error {
	return autoConvert_cluster_SleepModeConfigList_To_v1_SleepModeConfigList(in, out, s)
}

func autoConvert_v1_SleepModeConfigSpec_To_cluster_SleepModeConfigSpec(in *SleepModeConfigSpec, out *cluster.SleepModeConfigSpec, s conversion.Scope) error {
	out.ForceSleep = in.ForceSleep
	out.ForceSleepDuration = (*int64)(unsafe.Pointer(in.ForceSleepDuration))
	out.DeleteAllPods = in.DeleteAllPods
	out.DeleteAfter = in.DeleteAfter
	out.SleepAfter = in.SleepAfter
	return nil
}

// Convert_v1_SleepModeConfigSpec_To_cluster_SleepModeConfigSpec is an autogenerated conversion function.
func Convert_v1_SleepModeConfigSpec_To_cluster_SleepModeConfigSpec(in *SleepModeConfigSpec, out *cluster.SleepModeConfigSpec, s conversion.Scope) error {
	return autoConvert_v1_SleepModeConfigSpec_To_cluster_SleepModeConfigSpec(in, out, s)
}

func autoConvert_cluster_SleepModeConfigSpec_To_v1_SleepModeConfigSpec(in *cluster.SleepModeConfigSpec, out *SleepModeConfigSpec, s conversion.Scope) error {
	out.ForceSleep = in.ForceSleep
	out.ForceSleepDuration = (*int64)(unsafe.Pointer(in.ForceSleepDuration))
	out.DeleteAllPods = in.DeleteAllPods
	out.DeleteAfter = in.DeleteAfter
	out.SleepAfter = in.SleepAfter
	return nil
}

// Convert_cluster_SleepModeConfigSpec_To_v1_SleepModeConfigSpec is an autogenerated conversion function.
func Convert_cluster_SleepModeConfigSpec_To_v1_SleepModeConfigSpec(in *cluster.SleepModeConfigSpec, out *SleepModeConfigSpec, s conversion.Scope) error {
	return autoConvert_cluster_SleepModeConfigSpec_To_v1_SleepModeConfigSpec(in, out, s)
}

func autoConvert_v1_SleepModeConfigStatus_To_cluster_SleepModeConfigStatus(in *SleepModeConfigStatus, out *cluster.SleepModeConfigStatus, s conversion.Scope) error {
	out.LastActivity = in.LastActivity
	out.SleepingSince = in.SleepingSince
	out.ActiveConnections = in.ActiveConnections
	out.CurrentEpoch = (*cluster.EpochInfo)(unsafe.Pointer(in.CurrentEpoch))
	out.LastEpoch = (*cluster.EpochInfo)(unsafe.Pointer(in.LastEpoch))
	out.SleptLastThirtyDays = (*float64)(unsafe.Pointer(in.SleptLastThirtyDays))
	out.SleptLastSevenDays = (*float64)(unsafe.Pointer(in.SleptLastSevenDays))
	return nil
}

// Convert_v1_SleepModeConfigStatus_To_cluster_SleepModeConfigStatus is an autogenerated conversion function.
func Convert_v1_SleepModeConfigStatus_To_cluster_SleepModeConfigStatus(in *SleepModeConfigStatus, out *cluster.SleepModeConfigStatus, s conversion.Scope) error {
	return autoConvert_v1_SleepModeConfigStatus_To_cluster_SleepModeConfigStatus(in, out, s)
}

func autoConvert_cluster_SleepModeConfigStatus_To_v1_SleepModeConfigStatus(in *cluster.SleepModeConfigStatus, out *SleepModeConfigStatus, s conversion.Scope) error {
	out.LastActivity = in.LastActivity
	out.SleepingSince = in.SleepingSince
	out.ActiveConnections = in.ActiveConnections
	out.CurrentEpoch = (*EpochInfo)(unsafe.Pointer(in.CurrentEpoch))
	out.LastEpoch = (*EpochInfo)(unsafe.Pointer(in.LastEpoch))
	out.SleptLastThirtyDays = (*float64)(unsafe.Pointer(in.SleptLastThirtyDays))
	out.SleptLastSevenDays = (*float64)(unsafe.Pointer(in.SleptLastSevenDays))
	return nil
}

// Convert_cluster_SleepModeConfigStatus_To_v1_SleepModeConfigStatus is an autogenerated conversion function.
func Convert_cluster_SleepModeConfigStatus_To_v1_SleepModeConfigStatus(in *cluster.SleepModeConfigStatus, out *SleepModeConfigStatus, s conversion.Scope) error {
	return autoConvert_cluster_SleepModeConfigStatus_To_v1_SleepModeConfigStatus(in, out, s)
}

func autoConvert_v1_VirtualCluster_To_cluster_VirtualCluster(in *VirtualCluster, out *cluster.VirtualCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_VirtualClusterSpec_To_cluster_VirtualClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_VirtualClusterStatus_To_cluster_VirtualClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_VirtualCluster_To_cluster_VirtualCluster is an autogenerated conversion function.
func Convert_v1_VirtualCluster_To_cluster_VirtualCluster(in *VirtualCluster, out *cluster.VirtualCluster, s conversion.Scope) error {
	return autoConvert_v1_VirtualCluster_To_cluster_VirtualCluster(in, out, s)
}

func autoConvert_cluster_VirtualCluster_To_v1_VirtualCluster(in *cluster.VirtualCluster, out *VirtualCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cluster_VirtualClusterSpec_To_v1_VirtualClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cluster_VirtualClusterStatus_To_v1_VirtualClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cluster_VirtualCluster_To_v1_VirtualCluster is an autogenerated conversion function.
func Convert_cluster_VirtualCluster_To_v1_VirtualCluster(in *cluster.VirtualCluster, out *VirtualCluster, s conversion.Scope) error {
	return autoConvert_cluster_VirtualCluster_To_v1_VirtualCluster(in, out, s)
}

func autoConvert_v1_VirtualClusterList_To_cluster_VirtualClusterList(in *VirtualClusterList, out *cluster.VirtualClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.VirtualCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_VirtualClusterList_To_cluster_VirtualClusterList is an autogenerated conversion function.
func Convert_v1_VirtualClusterList_To_cluster_VirtualClusterList(in *VirtualClusterList, out *cluster.VirtualClusterList, s conversion.Scope) error {
	return autoConvert_v1_VirtualClusterList_To_cluster_VirtualClusterList(in, out, s)
}

func autoConvert_cluster_VirtualClusterList_To_v1_VirtualClusterList(in *cluster.VirtualClusterList, out *VirtualClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]VirtualCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_VirtualClusterList_To_v1_VirtualClusterList is an autogenerated conversion function.
func Convert_cluster_VirtualClusterList_To_v1_VirtualClusterList(in *cluster.VirtualClusterList, out *VirtualClusterList, s conversion.Scope) error {
	return autoConvert_cluster_VirtualClusterList_To_v1_VirtualClusterList(in, out, s)
}

func autoConvert_v1_VirtualClusterSpec_To_cluster_VirtualClusterSpec(in *VirtualClusterSpec, out *cluster.VirtualClusterSpec, s conversion.Scope) error {
	out.VirtualClusterSpec = in.VirtualClusterSpec
	return nil
}

// Convert_v1_VirtualClusterSpec_To_cluster_VirtualClusterSpec is an autogenerated conversion function.
func Convert_v1_VirtualClusterSpec_To_cluster_VirtualClusterSpec(in *VirtualClusterSpec, out *cluster.VirtualClusterSpec, s conversion.Scope) error {
	return autoConvert_v1_VirtualClusterSpec_To_cluster_VirtualClusterSpec(in, out, s)
}

func autoConvert_cluster_VirtualClusterSpec_To_v1_VirtualClusterSpec(in *cluster.VirtualClusterSpec, out *VirtualClusterSpec, s conversion.Scope) error {
	out.VirtualClusterSpec = in.VirtualClusterSpec
	return nil
}

// Convert_cluster_VirtualClusterSpec_To_v1_VirtualClusterSpec is an autogenerated conversion function.
func Convert_cluster_VirtualClusterSpec_To_v1_VirtualClusterSpec(in *cluster.VirtualClusterSpec, out *VirtualClusterSpec, s conversion.Scope) error {
	return autoConvert_cluster_VirtualClusterSpec_To_v1_VirtualClusterSpec(in, out, s)
}

func autoConvert_v1_VirtualClusterStatus_To_cluster_VirtualClusterStatus(in *VirtualClusterStatus, out *cluster.VirtualClusterStatus, s conversion.Scope) error {
	out.VirtualClusterStatus = in.VirtualClusterStatus
	return nil
}

// Convert_v1_VirtualClusterStatus_To_cluster_VirtualClusterStatus is an autogenerated conversion function.
func Convert_v1_VirtualClusterStatus_To_cluster_VirtualClusterStatus(in *VirtualClusterStatus, out *cluster.VirtualClusterStatus, s conversion.Scope) error {
	return autoConvert_v1_VirtualClusterStatus_To_cluster_VirtualClusterStatus(in, out, s)
}

func autoConvert_cluster_VirtualClusterStatus_To_v1_VirtualClusterStatus(in *cluster.VirtualClusterStatus, out *VirtualClusterStatus, s conversion.Scope) error {
	out.VirtualClusterStatus = in.VirtualClusterStatus
	return nil
}

// Convert_cluster_VirtualClusterStatus_To_v1_VirtualClusterStatus is an autogenerated conversion function.
func Convert_cluster_VirtualClusterStatus_To_v1_VirtualClusterStatus(in *cluster.VirtualClusterStatus, out *VirtualClusterStatus, s conversion.Scope) error {
	return autoConvert_cluster_VirtualClusterStatus_To_v1_VirtualClusterStatus(in, out, s)
}
