// Code generated by client-gen. DO NOT EDIT.

package v1

type AccountExpansion interface{}

type HelmReleaseExpansion interface{}

type SleepModeConfigExpansion interface{}

type VirtualClusterExpansion interface{}
