// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	storagev1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalSpaceConstraints implements LocalSpaceConstraintInterface
type FakeLocalSpaceConstraints struct {
	Fake *FakeStorageV1
}

var localspaceconstraintsResource = schema.GroupVersionResource{Group: "storage.loft.sh", Version: "v1", Resource: "localspaceconstraints"}

var localspaceconstraintsKind = schema.GroupVersionKind{Group: "storage.loft.sh", Version: "v1", Kind: "LocalSpaceConstraint"}

// Get takes name of the localSpaceConstraint, and returns the corresponding localSpaceConstraint object, and an error if there is any.
func (c *FakeLocalSpaceConstraints) Get(ctx context.Context, name string, options v1.GetOptions) (result *storagev1.LocalSpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localspaceconstraintsResource, name), &storagev1.LocalSpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalSpaceConstraint), err
}

// List takes label and field selectors, and returns the list of LocalSpaceConstraints that match those selectors.
func (c *FakeLocalSpaceConstraints) List(ctx context.Context, opts v1.ListOptions) (result *storagev1.LocalSpaceConstraintList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localspaceconstraintsResource, localspaceconstraintsKind, opts), &storagev1.LocalSpaceConstraintList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &storagev1.LocalSpaceConstraintList{ListMeta: obj.(*storagev1.LocalSpaceConstraintList).ListMeta}
	for _, item := range obj.(*storagev1.LocalSpaceConstraintList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localSpaceConstraints.
func (c *FakeLocalSpaceConstraints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localspaceconstraintsResource, opts))
}

// Create takes the representation of a localSpaceConstraint and creates it.  Returns the server's representation of the localSpaceConstraint, and an error, if there is any.
func (c *FakeLocalSpaceConstraints) Create(ctx context.Context, localSpaceConstraint *storagev1.LocalSpaceConstraint, opts v1.CreateOptions) (result *storagev1.LocalSpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localspaceconstraintsResource, localSpaceConstraint), &storagev1.LocalSpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalSpaceConstraint), err
}

// Update takes the representation of a localSpaceConstraint and updates it. Returns the server's representation of the localSpaceConstraint, and an error, if there is any.
func (c *FakeLocalSpaceConstraints) Update(ctx context.Context, localSpaceConstraint *storagev1.LocalSpaceConstraint, opts v1.UpdateOptions) (result *storagev1.LocalSpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localspaceconstraintsResource, localSpaceConstraint), &storagev1.LocalSpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalSpaceConstraint), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalSpaceConstraints) UpdateStatus(ctx context.Context, localSpaceConstraint *storagev1.LocalSpaceConstraint, opts v1.UpdateOptions) (*storagev1.LocalSpaceConstraint, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localspaceconstraintsResource, "status", localSpaceConstraint), &storagev1.LocalSpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalSpaceConstraint), err
}

// Delete takes name of the localSpaceConstraint and deletes it. Returns an error if one occurs.
func (c *FakeLocalSpaceConstraints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(localspaceconstraintsResource, name, opts), &storagev1.LocalSpaceConstraint{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalSpaceConstraints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localspaceconstraintsResource, listOpts)

	_, err := c.Fake.Invokes(action, &storagev1.LocalSpaceConstraintList{})
	return err
}

// Patch applies the patch and returns the patched localSpaceConstraint.
func (c *FakeLocalSpaceConstraints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *storagev1.LocalSpaceConstraint, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localspaceconstraintsResource, name, pt, data, subresources...), &storagev1.LocalSpaceConstraint{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalSpaceConstraint), err
}
