// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	storagev1 "github.com/loft-sh/agentapi/v2/pkg/apis/loft/storage/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalClusterRoleTemplates implements LocalClusterRoleTemplateInterface
type FakeLocalClusterRoleTemplates struct {
	Fake *FakeStorageV1
}

var localclusterroletemplatesResource = schema.GroupVersionResource{Group: "storage.loft.sh", Version: "v1", Resource: "localclusterroletemplates"}

var localclusterroletemplatesKind = schema.GroupVersionKind{Group: "storage.loft.sh", Version: "v1", Kind: "LocalClusterRoleTemplate"}

// Get takes name of the localClusterRoleTemplate, and returns the corresponding localClusterRoleTemplate object, and an error if there is any.
func (c *FakeLocalClusterRoleTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *storagev1.LocalClusterRoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localclusterroletemplatesResource, name), &storagev1.LocalClusterRoleTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalClusterRoleTemplate), err
}

// List takes label and field selectors, and returns the list of LocalClusterRoleTemplates that match those selectors.
func (c *FakeLocalClusterRoleTemplates) List(ctx context.Context, opts v1.ListOptions) (result *storagev1.LocalClusterRoleTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localclusterroletemplatesResource, localclusterroletemplatesKind, opts), &storagev1.LocalClusterRoleTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &storagev1.LocalClusterRoleTemplateList{ListMeta: obj.(*storagev1.LocalClusterRoleTemplateList).ListMeta}
	for _, item := range obj.(*storagev1.LocalClusterRoleTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localClusterRoleTemplates.
func (c *FakeLocalClusterRoleTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localclusterroletemplatesResource, opts))
}

// Create takes the representation of a localClusterRoleTemplate and creates it.  Returns the server's representation of the localClusterRoleTemplate, and an error, if there is any.
func (c *FakeLocalClusterRoleTemplates) Create(ctx context.Context, localClusterRoleTemplate *storagev1.LocalClusterRoleTemplate, opts v1.CreateOptions) (result *storagev1.LocalClusterRoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localclusterroletemplatesResource, localClusterRoleTemplate), &storagev1.LocalClusterRoleTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalClusterRoleTemplate), err
}

// Update takes the representation of a localClusterRoleTemplate and updates it. Returns the server's representation of the localClusterRoleTemplate, and an error, if there is any.
func (c *FakeLocalClusterRoleTemplates) Update(ctx context.Context, localClusterRoleTemplate *storagev1.LocalClusterRoleTemplate, opts v1.UpdateOptions) (result *storagev1.LocalClusterRoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localclusterroletemplatesResource, localClusterRoleTemplate), &storagev1.LocalClusterRoleTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalClusterRoleTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalClusterRoleTemplates) UpdateStatus(ctx context.Context, localClusterRoleTemplate *storagev1.LocalClusterRoleTemplate, opts v1.UpdateOptions) (*storagev1.LocalClusterRoleTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localclusterroletemplatesResource, "status", localClusterRoleTemplate), &storagev1.LocalClusterRoleTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalClusterRoleTemplate), err
}

// Delete takes name of the localClusterRoleTemplate and deletes it. Returns an error if one occurs.
func (c *FakeLocalClusterRoleTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(localclusterroletemplatesResource, name, opts), &storagev1.LocalClusterRoleTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalClusterRoleTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localclusterroletemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &storagev1.LocalClusterRoleTemplateList{})
	return err
}

// Patch applies the patch and returns the patched localClusterRoleTemplate.
func (c *FakeLocalClusterRoleTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *storagev1.LocalClusterRoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localclusterroletemplatesResource, name, pt, data, subresources...), &storagev1.LocalClusterRoleTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*storagev1.LocalClusterRoleTemplate), err
}
