// Code generated by generator. DO NOT EDIT.

package install

import (
	"github.com/loft-sh/agentapi/pkg/apis/kiosk/tenancy"
	"github.com/loft-sh/agentapi/pkg/apis/kiosk/tenancy/v1alpha1"
	"github.com/loft-sh/apiserver/pkg/builders"
	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
)

func init() {
	Install(builders.Scheme)
}

func Install(scheme *runtime.Scheme) {
	utilruntime.Must(v1alpha1.AddToScheme(scheme))
	utilruntime.Must(tenancy.AddToScheme(scheme))
	utilruntime.Must(addKnownTypes(scheme))
}

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(tenancy.SchemeGroupVersion,
		&tenancy.Account{},
		&tenancy.AccountList{},
		&tenancy.Space{},
		&tenancy.SpaceList{},
	)
	return nil
}
