// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	storagev1 "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned/typed/storage/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterQuotas implements ClusterQuotaInterface
type fakeClusterQuotas struct {
	*gentype.FakeClientWithList[*v1.ClusterQuota, *v1.ClusterQuotaList]
	Fake *FakeStorageV1
}

func newFakeClusterQuotas(fake *FakeStorageV1) storagev1.ClusterQuotaInterface {
	return &fakeClusterQuotas{
		gentype.NewFakeClientWithList[*v1.ClusterQuota, *v1.ClusterQuotaList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("clusterquotas"),
			v1.SchemeGroupVersion.WithKind("ClusterQuota"),
			func() *v1.ClusterQuota { return &v1.ClusterQuota{} },
			func() *v1.ClusterQuotaList { return &v1.ClusterQuotaList{} },
			func(dst, src *v1.ClusterQuotaList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ClusterQuotaList) []*v1.ClusterQuota { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ClusterQuotaList, items []*v1.ClusterQuota) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
