// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalUsers implements LocalUserInterface
type FakeLocalUsers struct {
	Fake *FakeStorageV1
}

var localusersResource = v1.SchemeGroupVersion.WithResource("localusers")

var localusersKind = v1.SchemeGroupVersion.WithKind("LocalUser")

// Get takes name of the localUser, and returns the corresponding localUser object, and an error if there is any.
func (c *FakeLocalUsers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LocalUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localusersResource, name), &v1.LocalUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalUser), err
}

// List takes label and field selectors, and returns the list of LocalUsers that match those selectors.
func (c *FakeLocalUsers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LocalUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localusersResource, localusersKind, opts), &v1.LocalUserList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.LocalUserList{ListMeta: obj.(*v1.LocalUserList).ListMeta}
	for _, item := range obj.(*v1.LocalUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localUsers.
func (c *FakeLocalUsers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localusersResource, opts))
}

// Create takes the representation of a localUser and creates it.  Returns the server's representation of the localUser, and an error, if there is any.
func (c *FakeLocalUsers) Create(ctx context.Context, localUser *v1.LocalUser, opts metav1.CreateOptions) (result *v1.LocalUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localusersResource, localUser), &v1.LocalUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalUser), err
}

// Update takes the representation of a localUser and updates it. Returns the server's representation of the localUser, and an error, if there is any.
func (c *FakeLocalUsers) Update(ctx context.Context, localUser *v1.LocalUser, opts metav1.UpdateOptions) (result *v1.LocalUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localusersResource, localUser), &v1.LocalUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalUsers) UpdateStatus(ctx context.Context, localUser *v1.LocalUser, opts metav1.UpdateOptions) (*v1.LocalUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localusersResource, "status", localUser), &v1.LocalUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalUser), err
}

// Delete takes name of the localUser and deletes it. Returns an error if one occurs.
func (c *FakeLocalUsers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(localusersResource, name, opts), &v1.LocalUser{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalUsers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localusersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.LocalUserList{})
	return err
}

// Patch applies the patch and returns the patched localUser.
func (c *FakeLocalUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localusersResource, name, pt, data, subresources...), &v1.LocalUser{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalUser), err
}
