// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/loft-sh/agentapi/v4/pkg/apis/loft/storage/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalTeams implements LocalTeamInterface
type FakeLocalTeams struct {
	Fake *FakeStorageV1
}

var localteamsResource = v1.SchemeGroupVersion.WithResource("localteams")

var localteamsKind = v1.SchemeGroupVersion.WithKind("LocalTeam")

// Get takes name of the localTeam, and returns the corresponding localTeam object, and an error if there is any.
func (c *FakeLocalTeams) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LocalTeam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localteamsResource, name), &v1.LocalTeam{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalTeam), err
}

// List takes label and field selectors, and returns the list of LocalTeams that match those selectors.
func (c *FakeLocalTeams) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LocalTeamList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localteamsResource, localteamsKind, opts), &v1.LocalTeamList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.LocalTeamList{ListMeta: obj.(*v1.LocalTeamList).ListMeta}
	for _, item := range obj.(*v1.LocalTeamList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localTeams.
func (c *FakeLocalTeams) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localteamsResource, opts))
}

// Create takes the representation of a localTeam and creates it.  Returns the server's representation of the localTeam, and an error, if there is any.
func (c *FakeLocalTeams) Create(ctx context.Context, localTeam *v1.LocalTeam, opts metav1.CreateOptions) (result *v1.LocalTeam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localteamsResource, localTeam), &v1.LocalTeam{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalTeam), err
}

// Update takes the representation of a localTeam and updates it. Returns the server's representation of the localTeam, and an error, if there is any.
func (c *FakeLocalTeams) Update(ctx context.Context, localTeam *v1.LocalTeam, opts metav1.UpdateOptions) (result *v1.LocalTeam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localteamsResource, localTeam), &v1.LocalTeam{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalTeam), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalTeams) UpdateStatus(ctx context.Context, localTeam *v1.LocalTeam, opts metav1.UpdateOptions) (*v1.LocalTeam, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localteamsResource, "status", localTeam), &v1.LocalTeam{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalTeam), err
}

// Delete takes name of the localTeam and deletes it. Returns an error if one occurs.
func (c *FakeLocalTeams) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(localteamsResource, name, opts), &v1.LocalTeam{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalTeams) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localteamsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.LocalTeamList{})
	return err
}

// Patch applies the patch and returns the patched localTeam.
func (c *FakeLocalTeams) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalTeam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localteamsResource, name, pt, data, subresources...), &v1.LocalTeam{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.LocalTeam), err
}
