// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/loft-sh/agentapi/v4/pkg/clientset/versioned/typed/storage/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeStorageV1 struct {
	*testing.Fake
}

func (c *FakeStorageV1) ClusterQuotas() v1.ClusterQuotaInterface {
	return &FakeClusterQuotas{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeStorageV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
